#!/usr/bin/env python3
"""Render the hand-authored 16x16 pixel icon set (see docs/design/icons.md).

Every icon is a 16x16 grid of palette letters. Only the fill is authored: the
generator adds the 1-px dark outline (#0a1020) around the silhouette and lights
uppercase colours from the top-left (highlight on edges facing up/left, shadow
on edges facing down/right), so every icon shares one outline weight and one
light direction. Lowercase letters are flat colours for hand-placed details.
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "assets" / "icons"
SIZE = 16
INK = "#0a1020"
BG = "#1c2233"

# Flat colours: theme tokens from src/client/ui/ui_kit.gd (plus the bar colours).
FLAT = {
    "k": INK,
    "g": "#f0c85a",  # GOLD
    "o": "#f0a040",  # WARN
    "t": "#f2f2f5",  # TEXT
    "b": "#b3b4c0",  # BORDER
    "d": "#e05a4f",  # DANGER
    "r": "#d8453c",  # BAR_HP
    "p": "#f8aca0",  # ENEMY
    "s": "#5fb563",  # HP_FILL
    "a": "#8fd0f0",  # ALLY
    "e": "#3b9ae1",  # BAR_ENERGY
    "l": "#454b5e",  # SLATE
    "m": "#58607a",  # SLATE_HOVER
    "n": "#83df76",  # SUCCESS
}
# Lit colours: letter -> (base, highlight or None, shadow or None).
LIT = {
    "G": ("g", None, "o"),
    "T": ("t", None, "b"),
    "D": ("d", "p", "r"),
    "S": ("n", None, "s"),
    "E": ("e", "a", None),
    "W": ("o", None, "d"),
    "L": ("m", None, "l"),
    "P": ("p", None, "d"),
}
MAX_COLOURS = 5          # distinct non-outline colours per icon
MIN_BRIGHT = 20          # bright non-outline pixels per icon
MIN_MASK_DIFF = 16       # alpha pixels that must differ between any two icons

PATTERNS = {
    # --- battle actions -------------------------------------------------
    "fight": (  # one raised sword
        "................",
        ".......T........",
        "......TTT.......",
        "......TTT.......",
        "......TTT.......",
        "......TTT.......",
        "......TTT.......",
        "......TTT.......",
        "......TTT.......",
        "......TTT.......",
        "...GGGGGGGGG....",
        ".......W........",
        ".......W........",
        "......GGG.......",
        "................",
        "................",
    ),
    "items": (  # backpack
        "................",
        "......oooo......",
        ".....o....o.....",
        "....WWWWWWWW....",
        "...WWWWWWWWWW...",
        "..WWWWWWWWWWWW..",
        "..WddddddddddW..",
        "..WWWWWggWWWWW..",
        "..WWWWWggWWWWW..",
        "..WWWWWWWWWWWW..",
        "..WWWWWWWWWWWW..",
        "..WWddddddddWW..",
        "..WWddddddddWW..",
        "..WWWWWggWWWWW..",
        "...WWWWWWWWWW...",
        "................",
    ),
    "focus": (  # watchful eye
        "................",
        "................",
        "................",
        "................",
        ".....TTTTTT.....",
        "...TTTEEEETTT...",
        "..TTTEaEEEETTT..",
        ".TTTTEEkkEETTTT.",
        ".TTTTEEkkEETTTT.",
        "..TTTEEEEEETTT..",
        "...TTTEEEETTT...",
        ".....TTTTTT.....",
        "................",
        "................",
        "................",
        "................",
    ),
    "strike": (  # three slash marks
        "................",
        ".........T......",
        ".......TT...T...",
        "......TT..TT....",
        ".....TT..TT...T.",
        "....TT..TT..TT..",
        "...TT..TT..TT...",
        "..TT..TT..TT....",
        ".T...TT..TT.....",
        "....TT..TT......",
        "...TT..TT.......",
        "..T...TT........",
        ".....T..........",
        "................",
        "................",
        "................",
    ),
    "guard": (  # heater shield with a plus
        "................",
        "..GGGGGGGGGGGG..",
        "..GGGGGTTGGGGG..",
        "..GGGGGTTGGGGG..",
        "..GGGTTTTTTGGG..",
        "..GGGTTTTTTGGG..",
        "..GGGGGTTGGGGG..",
        "..GGGGGTTGGGGG..",
        "...GGGGGGGGGG...",
        "...GGGGGGGGGG...",
        "....GGGGGGGG....",
        ".....GGGGGG.....",
        "......GGGG......",
        ".......GG.......",
        "................",
        "................",
    ),
    "defend": (  # tall tower shield, gold rim and boss
        "................",
        ".....GGGGGG.....",
        "....GTTTTTTG....",
        "...GTTTTTTTTG...",
        "...GTTTbbTTTG...",
        "...GTTTbbTTTG...",
        "...GTTTGGTTTG...",
        "...GTTGGGGTTG...",
        "...GTTGGGGTTG...",
        "...GTTTGGTTTG...",
        "...GTTTbbTTTG...",
        "...GTTTbbTTTG...",
        "....GTTbbTTG....",
        ".....GTTTTG.....",
        "......GGGG......",
        "................",
    ),
    "flee": (  # running figure with motion lines
        "................",
        "..........TT....",
        "..........TT....",
        "................",
        "........TTTT....",
        "...bb..TTTTTTT..",
        "......TTTTT..TT.",
        "..bb.TT.TTT.....",
        "........TTT.....",
        "...bb..TTTTT....",
        "......TT...TT...",
        ".....TT.....TT..",
        "....TT.......T..",
        "...TT...........",
        "................",
        "................",
    ),
    "skill": (  # four-point spark with a small twinkle
        "................",
        "................",
        "......E.........",
        "......E......a..",
        "......E.....aaa.",
        ".....EEE.....a..",
        ".....EEE........",
        "....EEtEE.......",
        ".EEEEtttEEEE....",
        "....EEtEE.......",
        ".....EEE........",
        ".....EEE........",
        "......E.........",
        "......E.........",
        "......E.........",
        "................",
    ),
    "ready": (  # check mark breaking out of a circle
        "................",
        "..............T.",
        "....SSSSSS...TT.",
        "...SSSSSSSS.TT..",
        "..SSSSSSSSSTT...",
        ".SSSSSSSSSTTS...",
        ".SSTSSSSSTTSS...",
        ".SSTTSSSTTSSS...",
        ".SSSTTSTTSSSS...",
        ".SSSSTTTSSSSS...",
        ".SSSSSTSSSSSS...",
        "..SSSSSSSSSS....",
        "...SSSSSSSS.....",
        "....SSSSSS......",
        "................",
        "................",
    ),
    "transfer": (  # arrow out, arrow back
        "................",
        "..........G.....",
        "..........GG....",
        ".GGGGGGGGGGGG...",
        ".GGGGGGGGGGGG...",
        "..........GG....",
        "..........G.....",
        "................",
        "................",
        ".....T..........",
        "....TT..........",
        "...TTTTTTTTTTTT.",
        "...TTTTTTTTTTTT.",
        "....TT..........",
        ".....T..........",
        "................",
    ),
    # --- resources ------------------------------------------------------
    "hp": (  # heart
        "................",
        "................",
        "...DDD....DDD...",
        "..DDDDD..DDDDD..",
        ".DDtDDDDDDDDDDD.",
        ".DDDDDDDDDDDDDD.",
        ".DDDDDDDDDDDDDD.",
        "..DDDDDDDDDDDD..",
        "...DDDDDDDDDD...",
        "....DDDDDDDD....",
        ".....DDDDDD.....",
        "......DDDD......",
        ".......DD.......",
        "................",
        "................",
        "................",
    ),
    "energy": (  # blue crystal with a bolt
        "................",
        ".......EE.......",
        "......EEEE......",
        ".....EEEEtE.....",
        "....EEEEtEEE....",
        "...EEEEtEEEEE...",
        "..EEEEttttEEEE..",
        "..EEEEEEtEEEEE..",
        "...EEEEtEEEEE...",
        "....EEtEEEEE....",
        ".....EEEEEE.....",
        "......EEEE......",
        ".......EE.......",
        "................",
        "................",
        "................",
    ),
    "gold": (  # coin stack with one coin in front
        "................",
        "................",
        "..GGGGGG........",
        "..oooooo........",
        ".GGGGGG.........",
        ".oooooo.........",
        "..GGGGGGkGGGG...",
        "..oooookGGGGGG..",
        ".GGGGGkGGGGGGGG.",
        ".oooookGGGooGGG.",
        "..GGGGkGGGooGGG.",
        "..ooookGGGGGGGG.",
        ".GGGGGGkGGGGGG..",
        ".oooooo.kGGGG...",
        "................",
        "................",
    ),
    "gems": (  # brilliant-cut gem
        "................",
        "................",
        "................",
        "....EEEEEEEE....",
        "...EEtEEEEaEE...",
        "..EEEEEEEEEEEE..",
        "..aaaaaaaaaaaa..",
        "...EEEEEEEEEE...",
        "....EEEEaEEE....",
        ".....EEEaEE.....",
        "......EEaE......",
        ".......EE.......",
        "................",
        "................",
        "................",
        "................",
    ),
    "exp": (  # green five-point star
        "................",
        ".......SS.......",
        ".......SS.......",
        "......SSSS......",
        "......SttS......",
        ".SSSSSSttSSSSSS.",
        "..SSSSSSSSSSSS..",
        "...SSSSSSSSSS...",
        "....SSSSSSSS....",
        "....SSSSSSSS....",
        "...SSSSSSSSSS...",
        "...SSSS..SSSS...",
        "..SSS......SSS..",
        "..SS........SS..",
        "................",
        "................",
    ),
    "level": (  # up arrow on a step
        "................",
        ".......GG.......",
        "......GGGG......",
        ".....GGGGGG.....",
        "....GGGGGGGG....",
        "...GGGGGGGGGG...",
        "......GGGG......",
        "......GGGG......",
        "......GGGG......",
        "......GGGG......",
        "................",
        "..TTTTTTTTTTTT..",
        "..TTTTTTTTTTTT..",
        "................",
        "................",
        "................",
    ),
    # --- attributes -----------------------------------------------------
    "str": (  # flexed arm
        "................",
        "..WWWWW.........",
        ".WWWWWWW........",
        ".WdWdWdW........",
        ".WWWWWWW........",
        "..WWWWW.........",
        "...WWW....WWW...",
        "...WWW..WWWWWW..",
        "...WWW.WWWWWWWW.",
        "...WWWdWWWWWWWW.",
        "...WWWWWWWWWWWW.",
        "....WWWWWWWWWWW.",
        "......WWWWWWWWW.",
        "................",
        "................",
        "................",
    ),
    "dex": (  # winged boot
        "................",
        ".T..............",
        ".TT..GGGGG......",
        ".TTT.WWWWW......",
        "..TTTWWWWW......",
        ".TTTTWWWWW......",
        "..TTTWWWWW......",
        "...TTWWWWW......",
        ".....WWWWW......",
        ".....WWWWWWW....",
        ".....WWWWWWWWW..",
        ".....WWWWWWWWWW.",
        ".....GGGGGGGGGG.",
        "................",
        "................",
        "................",
    ),
    "con": (  # heart guarded by a shield
        "................",
        "..DD..DD........",
        ".DDDDDDDD.......",
        ".DDDDDDDD.......",
        "..DDDDDDD.......",
        "...DDDgggggggg..",
        "....DDgttttttg..",
        "......gttttttg..",
        "......gtttgttg..",
        "......gtggggtg..",
        ".......gttgtg...",
        "........gttg....",
        ".........gg.....",
        "................",
        "................",
        "................",
    ),
    "int": (  # brain
        "................",
        "................",
        "...PPPP.PPPP....",
        "..PPPPPPPPPPPP..",
        ".PPPdPPPdPPPPPP.",
        ".PPPPddPPdPPdPP.",
        ".PdPPPPdPPPdPPP.",
        ".PPddPPdPPPPdPP.",
        "..PPPdPPPddPPPP.",
        "...PPPPPPPPPPP..",
        "..........PPP...",
        "..........PP....",
        "................",
        "................",
        "................",
        "................",
    ),
    "fth": (  # holy cross on a rayed sun
        "................",
        ".......oo.......",
        "..o....oo....o..",
        "...o.GGGGGG.o...",
        "....GGGTTGGG....",
        "...GGGGTTGGGG...",
        "...GGTTTTTTGG...",
        ".ooGGTTTTTTGGoo.",
        ".ooGGGGTTGGGGoo.",
        "...GGGGTTGGGG...",
        "...GGGGTTGGGG...",
        "....GGGTTGGG....",
        "...o.GGGGGG.o...",
        "..o....oo....o..",
        ".......oo.......",
        "................",
    ),
    "cha": (  # speech bubble with a heart
        "................",
        "...TTTTTTTTTT...",
        "..TTTTTTTTTTTT..",
        ".TTTTDDTTDDTTTT.",
        ".TTTDDDDDDDDTTT.",
        ".TTTDDDDDDDDTTT.",
        ".TTTTDDDDDDTTTT.",
        ".TTTTTDDDDTTTTT.",
        "..TTTTTDDTTTTT..",
        "...TTTTTTTTTT...",
        "...TTT..........",
        "..TT............",
        ".T..............",
        "................",
        "................",
        "................",
    ),
    "lck": (  # four-leaf clover
        "................",
        "...SSS....SSS...",
        "..SSSSS..SSSSS..",
        "..SSSSSSSSSSSS..",
        "...SSSSssSSSS...",
        "....SSssssSS....",
        "...SSSSssSSSS...",
        "..SSSSSSSSSSSS..",
        "..SSSSS..SSSSS..",
        "...SSS.ss.SSS...",
        ".......ss.......",
        "........ss......",
        ".........ss.....",
        "................",
        "................",
        "................",
    ),
    # --- statuses -------------------------------------------------------
    "poison": (  # green drop with bubbles
        "................",
        "............S...",
        "......S.........",
        ".....SSS...SS...",
        ".....SSS...SS...",
        "....SSSSS.......",
        "...SSSSSSS..S...",
        "...SSSSSSS......",
        "..SStSSSSSS.....",
        "..SStSSSSSS.....",
        "..SSSSSSSSS.....",
        "..SSSSSSSSS.....",
        "...SSSSSSS......",
        "....SSSSS.......",
        "................",
        "................",
    ),
    "bleed": (  # big and small blood drops
        "................",
        "........D.......",
        "........D.......",
        ".......DDD......",
        ".......DDD......",
        "......DDDDD.....",
        ".....DDDDDDD....",
        ".....DDDDDDD....",
        "....DDDDDDDDD...",
        "....DDDDDDDDD...",
        "..D.DDDDDDDDD...",
        ".DDD.DDDDDDD....",
        ".DDD..DDDDD.....",
        "................",
        "................",
        "................",
    ),
    "burn": (  # layered flame
        "................",
        "......d.........",
        "......dd........",
        ".....ddd...d....",
        ".....dddd..dd...",
        "....ddddd.ddd...",
        "....dddoddddd...",
        "...ddddooddddd..",
        "...dddoooodddd..",
        "..dddooggoodddd.",
        "..ddoogggggoddd.",
        "..ddoogggggoodd.",
        "...ddoogggoodd..",
        "....dddddddd....",
        "................",
        "................",
    ),
    "stun": (  # lightning bolt
        "................",
        ".......GGGGGG...",
        "......GGGGGG....",
        ".....GGGGGG.....",
        "....GGGGGG......",
        "...GGGGGGGGGGG..",
        "..GGGGGGGGGGG...",
        "........GGGG....",
        ".......GGGG.....",
        "......GGGG......",
        ".....GGG........",
        "....GG..........",
        "...G............",
        "................",
        "................",
        "................",
    ),
    "weak": (  # broken sword and a falling arrow
        "................",
        "......T.........",
        ".....TTT........",
        ".....TTT...dd...",
        ".....TT....dd...",
        "...........dd...",
        "....T.T....dd...",
        "....TTT....dd...",
        "....TTT..dddddd.",
        "....TTT...dddd..",
        "....TTT....dd...",
        "..GGGGGGG.......",
        ".....W..........",
        ".....W..........",
        "....GGG.........",
        "................",
    ),
    "shield": (  # blue kite shield
        "................",
        "......EEEE......",
        "....EEEEEEEE....",
        "...EEEEEEEEEE...",
        "..EEEEEaaEEEEE..",
        "..EEEEEaaEEEEE..",
        "..EEEEEaaEEEEE..",
        "...EEEEaaEEEE...",
        "...EEEEaaEEEE...",
        "....EEEaaEEE....",
        "....EEEaaEEE....",
        ".....EEaaEE.....",
        "......EEEE......",
        "......EEEE......",
        ".......EE.......",
        "................",
    ),
    "regen": (  # green heart with a plus
        "................",
        "............T...",
        "...........TTT..",
        "............T...",
        "..SSS..SSS......",
        ".SSSSSSSSSS.....",
        ".SSSSTTSSSS.....",
        ".SSTTTTTTSS.....",
        ".SSTTTTTTSS.....",
        "..SSSTTSSS......",
        "...SSSSSS.......",
        "....SSSS........",
        ".....SS.........",
        "................",
        "................",
        "................",
    ),
    "dodge": (  # swerving arrow
        "................",
        "..........E.....",
        "..........EE....",
        "......EEEEEEE...",
        ".....EEEEEEEEE..",
        "....EEE...EE....",
        "...EEE....E.....",
        "...EE...........",
        "..EEE...........",
        "..EE....aaaa....",
        "..EE............",
        "..EE..aaaaaa....",
        "..EE............",
        "..EE....aaaa....",
        "................",
        "................",
    ),
    "crit": (  # starburst with an exclamation mark
        "................",
        ".......WW.......",
        ".W.....WW.....W.",
        "..WW..WWWW..WW..",
        "..WWWWWWWWWWWW..",
        "...WWWGkkGWWW...",
        "...WWGGkkGGWW...",
        ".WWWWGGkkGGWWWW.",
        ".WWWWGGGGGGWWWW.",
        "...WWGGkkGGWW...",
        "...WWWGGGGWWW...",
        "..WWWWWWWWWWWW..",
        "..WW..WWWW..WW..",
        ".W.....WW.....W.",
        ".......WW.......",
        "................",
    ),
    # --- equipment slots ------------------------------------------------
    "weapon": (  # diagonal sword
        "................",
        ".............TT.",
        "............TT..",
        "...........TT...",
        "..........TT....",
        ".........TT.....",
        "........TT......",
        "...GG..TT.......",
        "....GGTT........",
        ".....GG.........",
        "....W.GG........",
        "...W...GG.......",
        ".GG.............",
        ".GG.............",
        "................",
        "................",
    ),
    "armor": (  # breastplate
        "................",
        "................",
        ".TTTT......TTTT.",
        ".TTTTT....TTTTT.",
        ".TTTTTTbbTTTTTT.",
        ".TTTTTTbbTTTTTT.",
        "..TTTTTbbTTTTT..",
        "...TTTTbbTTTT...",
        "...TTTTbbTTTT...",
        "...TTTTbbTTTT...",
        "...GGGGGGGGGG...",
        "...TTTTTTTTTT...",
        "....TTTTTTTT....",
        "................",
        "................",
        "................",
    ),
    "accessory": (  # pendant on a chain
        "................",
        "..G.........G...",
        "..G.........G...",
        "...G.......G....",
        "....G.....G.....",
        ".....G...G......",
        "......GGGG......",
        ".....GEEEEG.....",
        "....GEEEEEEG....",
        "....GEEEEEEG....",
        "....GEEEEEEG....",
        ".....GEEEEG.....",
        "......GGGG......",
        "................",
        "................",
        "................",
    ),
    "consumable": (  # potion bottle
        "................",
        "......oooo......",
        "......oooo......",
        "......tttt......",
        ".....tttttt.....",
        "....tttttttt....",
        "...tttttttttt...",
        "..tDDDDDDDDDDt..",
        "..DtDDDDDDDDDD..",
        "..DtDDDDDDDDDD..",
        "..DDDDDDDDDDDD..",
        "...DDDDDDDDDD...",
        "....DDDDDDDD....",
        "................",
        "................",
        "................",
    ),
    # --- path / encounter -----------------------------------------------
    "combat": (  # crossed swords
        "................",
        ".TT..........TT.",
        "..TT........TT..",
        "...TT......TT...",
        "....TT....TT....",
        ".....TT..TT.....",
        "......TTTT......",
        ".......TT.......",
        "...G..TTTT..G...",
        "....GTT..TTG....",
        ".....G....G.....",
        "....W.G..G.W....",
        "...W...GG...W...",
        "..G..........G..",
        "................",
        "................",
    ),
    "elite": (  # horned skull
        "................",
        ".W............W.",
        ".WW..........WW.",
        "..WW........WW..",
        "..WWW......WWW..",
        "...WWTTTTTTWW...",
        "...TTTTTTTTTT...",
        "...TTTTTTTTTT...",
        "...TkkTTTTkkT...",
        "...TkkTTTTkkT...",
        "...TTTTkkTTTT...",
        "....TTTTTTTT....",
        ".....TbTbTbT....",
        ".....TTTTTT.....",
        "................",
        "................",
    ),
    "merchant": (  # market stall: striped awning over a counter
        "................",
        "...ddttddttdd...",
        "..ddttddttddtt..",
        ".ddttddttddttdd.",
        ".ddttddttddttdd.",
        ".dd..dd..dd..dd.",
        "..b..........b..",
        "..b..........b..",
        "..b..gg..gg..b..",
        "..b..gg..gg..b..",
        ".oooooooooooooo.",
        ".oooooooooooooo.",
        ".oo..........oo.",
        ".oo..........oo.",
        "................",
        "................",
    ),
    "rest": (  # campfire
        "................",
        "................",
        ".......d........",
        "......dd........",
        "......ddd.d.....",
        ".....ddoddd.....",
        ".....doooddd....",
        "....ddoogood....",
        "....dooggood....",
        ".....dogggod....",
        ".LLL..dddd..LLL.",
        "...LLLL..LLLL...",
        ".....LLLLLL.....",
        "...LLLL..LLLL...",
        ".LLL........LLL.",
        "................",
    ),
    "treasure": (  # chest
        "................",
        "................",
        "...WWWWWWWWWW...",
        "..WWWWWWWWWWWW..",
        ".WWWWWWWWWWWWWW.",
        ".GWWWWWWWWWWWWG.",
        ".kkkkkkGGkkkkkk.",
        ".GWWWWGkkGWWWWG.",
        ".GWWWWGGGGWWWWG.",
        ".GWWWWWWWWWWWWG.",
        ".GWWWWWWWWWWWWG.",
        ".GWWWWWWWWWWWWG.",
        ".GGGGGGGGGGGGGG.",
        "................",
        "................",
        "................",
    ),
    "story": (  # open book
        "................",
        "................",
        ".TTTT......TTTT.",
        ".TTTTTT..TTTTTT.",
        ".TTTTTTbbTTTTTT.",
        ".TbbbbTbbTbbbbT.",
        ".TTTTTTbbTTTTTT.",
        ".TbbbbTbbTbbbbT.",
        ".TTTTTTbbTTTTTT.",
        ".TbbbTTbbTbbbTT.",
        ".TTTTTTbbTTTTTT.",
        ".oooooooooooooo.",
        "...........d....",
        "...........d....",
        "................",
        "................",
    ),
    "class_trial": (  # challenge banner
        "................",
        "..gg............",
        "..tDDDDDDDDDDDD.",
        "..tDDDDDDDDDDD..",
        "..tDDDDggDDDD...",
        "..tDDDggggDD....",
        "..tDDDggggDD....",
        "..tDDDDggDDDD...",
        "..tDDDDDDDDDDD..",
        "..tDDDDDDDDDDDD.",
        "..t.............",
        "..t.............",
        "..t.............",
        "..t.............",
        ".ttt............",
        "................",
    ),
    "boss": (  # crowned skull with red eyes
        "................",
        "...G...GG...G...",
        "...GG.GGGG.GG...",
        "...GGGGGGGGGG...",
        "...GGGGGGGGGG...",
        "...TTTTTTTTTT...",
        "..TTTTTTTTTTTT..",
        "..TTTTTTTTTTTT..",
        "..TTddTTTTddTT..",
        "..TTddTTTTddTT..",
        "..TTTTTkkTTTTT..",
        "...TTTTTTTTTT...",
        "....TbTbTbTb....",
        "....TTTTTTTT....",
        "................",
        "................",
    ),
    # --- menus ----------------------------------------------------------
    "play": (  # bold play triangle
        "................",
        "................",
        "...GG...........",
        "...GGGG.........",
        "...GGGGGG.......",
        "...GGGGGGGG.....",
        "...GGGGGGGGGG...",
        "...GGGGGGGGGGGG.",
        "...GGGGGGGGGGGG.",
        "...GGGGGGGGGG...",
        "...GGGGGGGG.....",
        "...GGGGGG.......",
        "...GGGG.........",
        "...GG...........",
        "................",
        "................",
    ),
    "multiplayer": (  # two party members
        "................",
        "..........EE....",
        ".........EEEE...",
        "....TT...EEEE...",
        "...TTTT...EE....",
        "...TTTT.........",
        "....TT...EEEE...",
        "........EEEEEE..",
        "..TTTTTTkEEEEEE.",
        ".TTTTTTTTkEEEEE.",
        ".TTTTTTTTkEEEEE.",
        ".TTTTTTTTkEEEEE.",
        ".TTTTTTTTkEEEEE.",
        ".TTTTTTTT.......",
        "................",
        "................",
    ),
    "story_mode": (  # closed book with a bookmark
        "................",
        "..EEEEEEEEEE....",
        "..lEEEEEEEEEt...",
        "..lEEEEEEEEEt...",
        "..lEEEggggEEt...",
        "..lEEEgEEgEEt...",
        "..lEEEggggEEt...",
        "..lEEEEEEEEEt...",
        "..lEEEEEEEEEt...",
        "..lEEEEEEEEEt...",
        "..lEEEEEEEEEt...",
        "..lEEEEEEEEEt...",
        "..lEEEEEEEEEE...",
        "........g.......",
        "........g.......",
        "................",
    ),
    "settings": (  # gear
        "................",
        "......TTTT......",
        "..TT..TTTT..TT..",
        "..TTTTTTTTTTTT..",
        "...TTTTTTTTTT...",
        "...TTTTTTTTTT...",
        ".TTTTTT..TTTTTT.",
        ".TTTTT....TTTTT.",
        ".TTTTT....TTTTT.",
        ".TTTTTT..TTTTTT.",
        "...TTTTTTTTTT...",
        "...TTTTTTTTTT...",
        "..TTTTTTTTTTTT..",
        "..TT..TTTT..TT..",
        "......TTTT......",
        "................",
    ),
    "credits": (  # scroll of names
        "................",
        ".WWWWWWWWWWWWWW.",
        ".WWWWWWWWWWWWWW.",
        "..TTTTTTTTTTTT..",
        "..TbbbbbbbbbbT..",
        "..TTTTTTTTTTTT..",
        "..TbbbbbbbTTTT..",
        "..TTTTTTTTTTTT..",
        "..TbbbbbbbbbbT..",
        "..TTTTTTTTTTTT..",
        "..TbbbbbbTTTTT..",
        "..TTTTTTTTTTTT..",
        ".WWWWWWWWWWWWWW.",
        ".WWWWWWWWWWWWWW.",
        "................",
        "................",
    ),
    "back": (  # bold left arrow
        "................",
        "................",
        "......G.........",
        ".....GG.........",
        "....GGG.........",
        "...GGGG.........",
        "..GGGGGGGGGGGGG.",
        ".GGGGGGGGGGGGGG.",
        ".GGGGGGGGGGGGGG.",
        "..GGGGGGGGGGGGG.",
        "...GGGG.........",
        "....GGG.........",
        ".....GG.........",
        "......G.........",
        "................",
        "................",
    ),
    "quit": (  # power symbol
        "................",
        ".......DD.......",
        ".......DD.......",
        "....DD.DD.DD....",
        "...DDD.DD.DDD...",
        "..DDD..DD..DDD..",
        "..DD...DD...DD..",
        ".DD....DD....DD.",
        ".DD....DD....DD.",
        ".DD..........DD.",
        ".DD..........DD.",
        "..DD........DD..",
        "..DDD......DDD..",
        "...DDDDDDDDDD...",
        ".....DDDDDD.....",
        "................",
    ),
    "save": (  # floppy disk
        "................",
        ".EEEEEEEEEEEE...",
        ".EEbbbbbbbbEEE..",
        ".EEbbbbbkkbEEEE.",
        ".EEbbbbbkkbEEEE.",
        ".EEbbbbbbbbEEEE.",
        ".EEEEEEEEEEEEEE.",
        ".EEttttttttttEE.",
        ".EEttttttttttEE.",
        ".EEttttttttttEE.",
        ".EEttttttttttEE.",
        ".EEttttttttttEE.",
        ".EEttttttttttEE.",
        ".EEEEEEEEEEEEEE.",
        "................",
        "................",
    ),
    "lock": (  # padlock
        "................",
        ".....TTTTTT.....",
        "....TTTTTTTT....",
        "....TT....TT....",
        "....TT....TT....",
        "....TT....TT....",
        "..GGGGGGGGGGGG..",
        "..GGGGGGGGGGGG..",
        "..GGGGGkkGGGGG..",
        "..GGGGGkkGGGGG..",
        "..GGGGGGkGGGGG..",
        "..GGGGGGkGGGGG..",
        "..GGGGGGGGGGGG..",
        "..GGGGGGGGGGGG..",
        "................",
        "................",
    ),
    "info": (  # bold letter i
        "................",
        "......EEEE......",
        "......EEEE......",
        "......EEEE......",
        "................",
        "....EEEEEE......",
        "....EEEEEE......",
        "......EEEE......",
        "......EEEE......",
        "......EEEE......",
        "......EEEE......",
        "......EEEE......",
        "....EEEEEEEE....",
        "....EEEEEEEE....",
        "................",
        "................",
    ),
    "warning": (  # alert triangle
        "................",
        ".......WW.......",
        "......WWWW......",
        "......WkkW......",
        ".....WWkkWW.....",
        ".....WWkkWW.....",
        "....WWWkkWWW....",
        "....WWWkkWWW....",
        "...WWWWkkWWWW...",
        "...WWWWWWWWWW...",
        "..WWWWWkkWWWWW..",
        "..WWWWWkkWWWWW..",
        ".WWWWWWWWWWWWWW.",
        ".WWWWWWWWWWWWWW.",
        "................",
        "................",
    ),
}


def _is_fill(pattern, x, y):
    return 0 <= x < SIZE and 0 <= y < SIZE and pattern[y][x] != "."


def validate(name, pattern):
    if len(pattern) != SIZE:
        raise ValueError(f"{name}: expected {SIZE} rows, got {len(pattern)}")
    for y, row in enumerate(pattern):
        if len(row) != SIZE:
            raise ValueError(f"{name}: row {y} has {len(row)} cells: {row!r}")
        for x, cell in enumerate(row):
            if cell != "." and cell not in FLAT and cell not in LIT:
                raise ValueError(f"{name}: unknown colour {cell!r} at {x},{y}")
            if cell != "." and (x in (0, SIZE - 1) or y in (0, SIZE - 1)):
                raise ValueError(f"{name}: fill at {x},{y} leaves no room for the outline")


def shade(pattern, x, y):
    """Return the flat colour letter for a lit cell (light from the top-left)."""
    base, light, dark = LIT[pattern[y][x]]
    lit = not _is_fill(pattern, x - 1, y) or not _is_fill(pattern, x, y - 1)
    shadowed = not _is_fill(pattern, x + 1, y) or not _is_fill(pattern, x, y + 1)
    if lit and not shadowed and light:
        return light
    if shadowed and not lit and dark:
        return dark
    return base


def render_icon(pattern):
    image = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    for y in range(SIZE):
        for x in range(SIZE):
            cell = pattern[y][x]
            if cell == ".":
                near = any(_is_fill(pattern, x + dx, y + dy) for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)))
                if near:
                    image.putpixel((x, y), _rgba(INK))
                continue
            letter = shade(pattern, x, y) if cell in LIT else cell
            image.putpixel((x, y), _rgba(FLAT[letter]))
    return image


def _rgba(hex_colour):
    value = hex_colour.lstrip("#")
    return tuple(int(value[i:i + 2], 16) for i in (0, 2, 4)) + (255,)


def filename(name):
    # CON is a reserved DOS device name, even with an extension. Prefix it so
    # Godot can import and export the Constitution icon on Windows.
    return "_con" if name == "con" else name


def self_check(names):
    ink = _rgba(INK)
    seen_pixels, masks = {}, {}
    for name in names:
        validate(name, PATTERNS[name])
        image = render_icon(PATTERNS[name])
        pixels = tuple(image.getpixel((x, y)) for y in range(SIZE) for x in range(SIZE))
        if pixels in seen_pixels:
            raise ValueError(f"duplicate icon pixels: {name} and {seen_pixels[pixels]}")
        seen_pixels[pixels] = name
        mask = tuple(pixel[3] > 0 for pixel in pixels)
        for other, other_mask in masks.items():
            diff = sum(1 for a, b in zip(mask, other_mask) if a != b)
            if diff < MIN_MASK_DIFF:
                raise ValueError(f"{name} and {other} share a silhouette ({diff} alpha pixels differ, "
                                 f"need {MIN_MASK_DIFF})")
        masks[name] = mask
        colours = {pixel for pixel in pixels if pixel[3] > 0 and pixel != ink}
        if len(colours) > MAX_COLOURS:
            raise ValueError(f"{name} uses {len(colours)} colours besides the outline (max {MAX_COLOURS})")
        bright = 0
        for pixel in pixels:
            if pixel[3] == 0 or pixel == ink:
                continue
            luminance = (0.2126 * pixel[0] + 0.7152 * pixel[1] + 0.0722 * pixel[2]) / 255
            if luminance > 0.35:
                bright += 1
        if bright < MIN_BRIGHT:
            raise ValueError(f"{name} has only {bright} bright non-outline pixels (need {MIN_BRIGHT})")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    names = list(PATTERNS)
    self_check(names)
    for name, pattern in PATTERNS.items():
        render_icon(pattern).save(OUT / f"{filename(name)}.png")

    # Contact sheet: each icon at 1x and 3x on navy, labelled.
    cell_w, cell_h, scale = 170, 64, 3
    cols = 4
    rows = (len(names) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * cell_w, rows * cell_h), BG)
    draw = ImageDraw.Draw(sheet)
    try:
        font = ImageFont.truetype("arial.ttf", 12)
    except OSError:
        font = ImageFont.load_default()
    for index, name in enumerate(names):
        x, y = (index % cols) * cell_w, (index // cols) * cell_h
        icon = Image.open(OUT / f"{filename(name)}.png").convert("RGBA")
        sheet.paste(icon, (x + 6, y + 24), icon)
        big = icon.resize((SIZE * scale, SIZE * scale), Image.Resampling.NEAREST)
        sheet.paste(big, (x + 28, y + 8), big)
        draw.text((x + 84, y + 25), name, fill=FLAT["t"], font=font)
    sheet.save(OUT / "_contact.png")
    print(f"Wrote {len(names)} icons to {OUT}")


if __name__ == "__main__":
    main()
